server {
    listen 80;
    server_name www.broadscene.ai;

    location ^~ /.well-known/acme-challenge/ {
        allow all;
        root /usr/share/nginx/html;
        default_type "text/plain";
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 80;
    server_name api.broadscene.ai;

    location ^~ /.well-known/acme-challenge/ {
        allow all;
        root /usr/share/nginx/html;
        default_type "text/plain";
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name www.broadscene.ai;

    ssl_certificate /etc/letsencrypt/live/www.broadscene.ai/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.broadscene.ai/privkey.pem;

    # 当前保持不变：www -> ai-api
    location / {
        client_max_body_size 128M;
        proxy_connect_timeout 600s;
        proxy_send_timeout 600s;
        proxy_read_timeout 600s;
        proxy_pass http://host.docker.internal:3346;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;
    server_name api.broadscene.ai;

    ssl_certificate /etc/letsencrypt/live/api.broadscene.ai/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.broadscene.ai/privkey.pem;

    # 测试阶段：api -> website
    location / {
        client_max_body_size 128M;
        proxy_connect_timeout 600s;
        proxy_send_timeout 600s;
        proxy_read_timeout 600s;
        proxy_pass http://host.docker.internal:3347;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}